"""Static V3.4 source and tool registries.

The registry is deliberately explicit because V3.4 is about governance before
collection: every source/tool must have value, risk, cache, rate-limit and
credential policy before it can produce future ML evidence.
"""

from __future__ import annotations

from app.collectors.contracts import (
    CachePolicy,
    CollectorContract,
    RateLimitPolicy,
    SourceCapability,
    ToolEvaluationContract,
)

COLLECTOR_REGISTRY: tuple[CollectorContract, ...] = (
    CollectorContract(
        collector_key="spotify_official_artist_profile",
        source_key="spotify_web_api",
        source_name="Spotify Web API",
        source_type="streaming_api",
        base_url="https://api.spotify.com",
        access_method="official_api",
        extraction_method="client_credentials_api",
        requires_credentials=True,
        credential_env_vars=("SPOTIFY_CLIENT_ID", "SPOTIFY_CLIENT_SECRET"),
        rate_limit_policy=RateLimitPolicy(requests_per_minute=60, quota_cost_hint="standard_api_call", notes="Cache required before repeated artist refreshes."),
        cache_policy=CachePolicy(ttl_seconds=86_400),
        legal_risk="low",
        ml_value="high",
        cost_level="free_with_limits",
        trust_level="high",
        confidence="high",
        can_run_without_credentials=False,
        requires_review=False,
        capabilities=SourceCapability(can_provide_followers=True, can_provide_tags=True, can_provide_profile_url=True, can_provide_images=True, can_provide_releases=True),
        notes="Official source for popularity, followers, genres, image and releases. Real calls start in V3.4-B.",
    ),
    CollectorContract(
        collector_key="lastfm_official_artist_profile",
        source_key="lastfm_api",
        source_name="Last.fm API",
        source_type="music_api",
        base_url="https://ws.audioscrobbler.com/2.0/",
        access_method="official_api",
        extraction_method="api_key_api",
        requires_credentials=True,
        credential_env_vars=("LASTFM_API_KEY",),
        rate_limit_policy=RateLimitPolicy(requests_per_minute=60, quota_cost_hint="standard_api_call", notes="Coverage varies; no bulk calls without cache."),
        cache_policy=CachePolicy(ttl_seconds=86_400),
        legal_risk="low",
        ml_value="high",
        cost_level="free_with_limits",
        trust_level="medium",
        confidence="medium",
        can_run_without_credentials=False,
        capabilities=SourceCapability(can_provide_plays=True, can_provide_tags=True, can_provide_bio=True, can_provide_profile_url=True),
        notes="Good for listeners/playcounts/tags when artist coverage exists. Real calls start in V3.4-B.",
    ),
    CollectorContract(
        collector_key="musicbrainz_official_artist_profile",
        source_key="musicbrainz_api",
        source_name="MusicBrainz API",
        source_type="metadata_api",
        base_url="https://musicbrainz.org/ws/2",
        access_method="official_public_api",
        extraction_method="public_api_with_user_agent",
        requires_credentials=False,
        credential_env_vars=("MUSICBRAINZ_USER_AGENT",),
        rate_limit_policy=RateLimitPolicy(requests_per_minute=50, min_delay_seconds=1.0, quota_cost_hint="strict_public_api", notes="Respect MusicBrainz User-Agent and one-request-per-second style usage."),
        cache_policy=CachePolicy(ttl_seconds=604_800),
        legal_risk="low",
        ml_value="medium",
        cost_level="free_with_strict_rate_limit",
        trust_level="high",
        confidence="high",
        can_run_without_credentials=True,
        capabilities=SourceCapability(can_provide_tags=True, can_provide_profile_url=True, can_provide_releases=True),
        notes="Useful for identity metadata and disambiguation, not primary demand. Real calls start in V3.4-B.",
    ),
    CollectorContract(
        collector_key="youtube_official_artist_probe",
        source_key="youtube_data_api",
        source_name="YouTube Data API",
        source_type="video_api",
        base_url="https://www.googleapis.com/youtube/v3",
        access_method="official_api",
        extraction_method="api_key_quota_aware_probe",
        requires_credentials=True,
        credential_env_vars=("YOUTUBE_API_KEY",),
        rate_limit_policy=RateLimitPolicy(requests_per_minute=20, quota_cost_hint="quota_unit_sensitive", notes="Limit and cache are mandatory because search endpoints consume quota."),
        cache_policy=CachePolicy(ttl_seconds=604_800),
        legal_risk="low_medium",
        ml_value="high",
        cost_level="free_quota_limited",
        trust_level="medium",
        confidence="medium",
        can_run_without_credentials=False,
        requires_review=True,
        capabilities=SourceCapability(can_provide_followers=True, can_provide_plays=True, can_provide_recent_activity=True, can_provide_profile_url=True, can_provide_images=True),
        notes="Prepared in V3.4-A. Missing credentials must be reported as not_configured, not ignored.",
    ),
    CollectorContract(
        collector_key="soundcloud_official_access_probe",
        source_key="soundcloud_public_api",
        source_name="SoundCloud official/public access probe",
        source_type="streaming_api_or_public_pages",
        base_url="https://api.soundcloud.com",
        access_method="official_api_or_public_metadata_fallback",
        extraction_method="access_probe_then_metadata_only_fallback",
        requires_credentials=True,
        credential_env_vars=("SOUNDCLOUD_CLIENT_ID", "SOUNDCLOUD_CLIENT_SECRET"),
        rate_limit_policy=RateLimitPolicy(requests_per_minute=20, quota_cost_hint="access_unconfirmed", notes="No uncontrolled calls until access is confirmed."),
        cache_policy=CachePolicy(ttl_seconds=604_800),
        legal_risk="medium",
        ml_value="critical",
        cost_level="free_or_unknown",
        trust_level="medium",
        confidence="medium",
        can_run_without_credentials=False,
        requires_review=True,
        capabilities=SourceCapability(can_provide_followers=True, can_provide_plays=True, can_provide_recent_activity=True, can_provide_profile_url=True),
        notes="Priority hard-dance source. If official access is unavailable, V3.4-C prepares yt-dlp metadata-only fallback.",
    ),
    CollectorContract(
        collector_key="manual_external_profile_review",
        source_key="manual_csv_review",
        source_name="Manual CSV/data review",
        source_type="manual_review",
        base_url=None,
        access_method="csv_manual_review",
        extraction_method="manual_import_with_source_notes",
        requires_credentials=False,
        rate_limit_policy=RateLimitPolicy(requests_per_minute=None, notes="Manual imports are not network-bound but must remain auditable."),
        cache_policy=CachePolicy(enabled=True, ttl_seconds=None, notes="Manual data is persisted as traceable evidence, never prediction."),
        legal_risk="low",
        ml_value="medium",
        cost_level="manual_time",
        trust_level="variable",
        confidence="medium",
        can_run_without_credentials=True,
        requires_review=True,
        capabilities=SourceCapability(can_provide_followers=True, can_provide_plays=True, can_provide_tags=True, can_provide_bio=True, can_provide_events=True, can_provide_recent_activity=True, can_provide_profile_url=True, can_provide_images=True, can_provide_releases=True),
        notes="Fallback only when source URL, confidence and notes are explicit. Manual evidence is not prediction.",
    ),
)

TOOL_EVALUATION_REGISTRY: tuple[ToolEvaluationContract, ...] = (
    ToolEvaluationContract(
        tool_key="spotify_web_api_direct",
        source_target="spotify",
        source_key="spotify_web_api",
        tool_name="Spotify Web API direct client",
        tool_type="official_api",
        candidate_for="followers_popularity_genres_images_releases",
        access_method="client_credentials",
        license_name="platform_terms",
        license_risk="low_medium",
        legal_risk="low",
        maintenance_status="official",
        integration_complexity="low",
        data_quality_expectation="high",
        ml_value="high",
        decision="use_in_v3_4_b_with_cache",
        decision_reason="Official API already fits V3 needs and existing credentials are expected locally.",
        docs_url="https://developer.spotify.com/documentation/web-api",
        requires_credentials=True,
    ),
    ToolEvaluationContract(
        tool_key="lastfm_api_direct",
        source_target="lastfm",
        source_key="lastfm_api",
        tool_name="Last.fm API direct client",
        tool_type="official_api",
        candidate_for="listeners_playcounts_tags_bio",
        access_method="api_key",
        license_name="platform_terms",
        license_risk="low_medium",
        legal_risk="low",
        maintenance_status="official",
        integration_complexity="low",
        data_quality_expectation="medium_high",
        ml_value="high",
        decision="use_in_v3_4_b_with_cache",
        decision_reason="Useful demand signal with variable coverage; missing data must become explicit coverage gaps.",
        docs_url="https://www.last.fm/api",
        requires_credentials=True,
    ),
    ToolEvaluationContract(
        tool_key="musicbrainz_web_service",
        source_target="musicbrainz",
        source_key="musicbrainz_api",
        tool_name="MusicBrainz Web Service",
        tool_type="official_api",
        candidate_for="identity_metadata_disambiguation_releases",
        access_method="public_api_with_user_agent",
        license_name="open_data_platform_terms",
        license_risk="low",
        legal_risk="low",
        maintenance_status="official",
        integration_complexity="medium",
        data_quality_expectation="high_for_metadata",
        ml_value="medium",
        decision="use_in_v3_4_b_with_strict_rate_limit",
        decision_reason="Strong identity aid but not a primary popularity source.",
        docs_url="https://musicbrainz.org/doc/MusicBrainz_API",
        requires_credentials=False,
    ),
    ToolEvaluationContract(
        tool_key="youtube_data_api_direct",
        source_target="youtube",
        source_key="youtube_data_api",
        tool_name="YouTube Data API",
        tool_type="official_api",
        candidate_for="channel_video_views_activity",
        access_method="api_key_quota",
        license_name="platform_terms",
        license_risk="medium",
        legal_risk="low_medium",
        maintenance_status="official",
        integration_complexity="medium",
        data_quality_expectation="medium_high_after_identity_review",
        ml_value="high",
        decision="prepare_in_v3_4_b_require_key_limit_cache",
        decision_reason="Valuable for DJ sets and momentum, but quota and channel matching require strict controls.",
        docs_url="https://developers.google.com/youtube/v3",
        requires_credentials=True,
        requires_manual_review=True,
    ),
    ToolEvaluationContract(
        tool_key="soundcloud_official_api_probe",
        source_target="soundcloud",
        source_key="soundcloud_public_api",
        tool_name="SoundCloud official API/access probe",
        tool_type="official_api_probe",
        candidate_for="followers_tracks_plays_activity",
        access_method="official_or_access_unconfirmed",
        license_name="platform_terms",
        license_risk="medium",
        legal_risk="medium",
        maintenance_status="access_unconfirmed",
        integration_complexity="medium_high",
        data_quality_expectation="high_if_accessible",
        ml_value="critical",
        decision="probe_first_then_fallback_if_needed",
        decision_reason="SoundCloud is strategically important for the niche, but access must be verified before integration.",
        docs_url="https://developers.soundcloud.com/docs/api/guide",
        requires_credentials=True,
        requires_manual_review=True,
    ),
    ToolEvaluationContract(
        tool_key="yt_dlp_metadata_only",
        source_target="youtube_soundcloud",
        source_key=None,
        tool_name="yt-dlp metadata-only extractor",
        tool_type="open_source_extractor",
        candidate_for="youtube_soundcloud_public_metadata_candidates",
        access_method="public_metadata_only",
        license_name="Unlicense/public-domain style project license",
        license_risk="low_medium_requires_review",
        legal_risk="medium",
        maintenance_status="active_open_source",
        integration_complexity="medium",
        data_quality_expectation="medium_requires_identity_review",
        ml_value="high",
        decision="evaluate_in_v3_4_c_metadata_only_no_downloads",
        decision_reason="Python-native and strong docs. Must be metadata-only, cached, limited and never download audio/video.",
        docs_url="https://github.com/yt-dlp/yt-dlp/wiki/",
        repo_url="https://github.com/yt-dlp/yt-dlp",
        supports_cache=True,
        supports_rate_limit=True,
        requires_credentials=False,
        requires_manual_review=True,
        evaluation_payload={"allowed_mode": "metadata_only", "no_audio_video_download": True},
    ),
    ToolEvaluationContract(
        tool_key="newpipe_extractor_spike",
        source_target="youtube_soundcloud",
        source_key=None,
        tool_name="NewPipeExtractor",
        tool_type="open_source_extractor",
        candidate_for="youtube_soundcloud_public_metadata_spike",
        access_method="java_kotlin_library",
        license_name="GPL-3.0-or-later style project license",
        license_risk="high_requires_legal_review_before_integration",
        legal_risk="medium_high",
        maintenance_status="active_open_source",
        integration_complexity="high",
        data_quality_expectation="potentially_high",
        ml_value="high",
        decision="evaluated_not_integrated_in_v3_4_a",
        decision_reason="Potentially useful but Java/Kotlin integration and license impact are too heavy for the first Python backend path.",
        repo_url="https://github.com/TeamNewPipe/NewPipeExtractor",
        supports_cache=False,
        supports_rate_limit=False,
        requires_manual_review=True,
    ),
    ToolEvaluationContract(
        tool_key="httpx_beautifulsoup_static_pages",
        source_target="public_static_pages",
        source_key=None,
        tool_name="httpx + BeautifulSoup static metadata extractor",
        tool_type="controlled_scraper",
        candidate_for="public_html_meta_tags_titles_links",
        access_method="public_static_html",
        license_name="library_licenses",
        license_risk="low",
        legal_risk="medium_source_dependent",
        maintenance_status="stable_python_libraries",
        integration_complexity="low_medium",
        data_quality_expectation="medium",
        ml_value="medium",
        decision="prepare_policy_not_source_specific_yet",
        decision_reason="Allowed only for static public metadata with cache/rate limit and source-specific ToS review.",
        docs_url="https://www.crummy.com/software/BeautifulSoup/bs4/doc/",
        supports_cache=True,
        supports_rate_limit=True,
        requires_manual_review=True,
    ),
    ToolEvaluationContract(
        tool_key="playwright_last_resort",
        source_target="javascript_rendered_pages",
        source_key=None,
        tool_name="Playwright browser automation",
        tool_type="browser_scraper_last_resort",
        candidate_for="js_rendered_public_pages_only_when_worth_it",
        access_method="headless_browser",
        license_name="Apache-2.0",
        license_risk="low",
        legal_risk="medium_high_source_dependent",
        maintenance_status="active_open_source",
        integration_complexity="high",
        data_quality_expectation="medium",
        ml_value="medium",
        decision="last_resort_not_integrated_by_default",
        decision_reason="Too heavy and risky for default ingestion. Only consider after source-specific justification.",
        docs_url="https://playwright.dev/python/",
        supports_cache=True,
        supports_rate_limit=True,
        requires_manual_review=True,
    ),
)
